services:
  php: &php
    image: ghcr.io/shikorism/tissue-php
    restart: always
    env_file: .env
    volumes:
      - ./storage:/app/storage
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    image: ghcr.io/shikorism/tissue-nginx
    restart: always
    environment:
      PHP_APP_HOST: php
    ports:
      - 127.0.0.1:4545:80
    depends_on:
      - php

  scheduler:
    <<: *php
    command: php artisan schedule:work
